services:
  KL-backend:
    image: ghcr.io/bazaaer/klopta-backend:latest
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      # Backend routing
      - "traefik.http.routers.KL-backend.rule=Host(`${HOSTNAME}`) && PathPrefix(`/api`)"
      - "traefik.http.routers.KL-backend.entrypoints=websecure"
      - "traefik.http.routers.KL-backend.tls=true"
      - "traefik.http.routers.KL-backend.tls.certresolver=letsencrypt"
      - "traefik.http.services.KL-backend.loadbalancer.server.port=5000"
    environment:
      - MONGO_USER=root
      - MONGO_PASSWORD=examplepassword
      - MONGO_HOST=KL-mongodb
      - MONGO_PORT=27017
      - REDIS_HOST=KL-redis
      - REDIS_PORT=6379
      - RAY_SERVE_URL=http://KL-model:8000
      - RAY_DASHBOARD_URL=http://KL-model:8265
    networks:
      - KL-database_network
      - KL-model_network
      - traefik
    depends_on:
      - KL-mongodb
      - KL-redis

  KL-model:
    image: ghcr.io/bazaaer/klopta-model:latest
    restart: unless-stopped
    networks:
      - KL-model_network
    runtime: nvidia

  KL-frontend:
    image: ghcr.io/bazaaer/klopta-frontend:latest
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      # Frontend routing
      - "traefik.http.routers.KL-frontend.rule=Host(`${HOSTNAME}`) && !PathPrefix(`/api`)"
      - "traefik.http.routers.KL-frontend.entrypoints=websecure"
      - "traefik.http.routers.KL-frontend.tls=true"
      - "traefik.http.routers.KL-frontend.tls.certresolver=letsencrypt"
    networks:
      - traefik

  KL-mongodb:
    image: mongo:6
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=examplepassword
    volumes:
      - KL-mongo_data:/data/db
    networks:
      - KL-database_network

  KL-redis:
    image: redis:latest
    restart: unless-stopped
    volumes:
      - KL-redis_data:/data
    networks:
      - KL-database_network

networks:
  KL-database_network:
    driver: bridge
  KL-model_network:
    driver: bridge
  traefik:
    external: true

volumes:
  KL-mongo_data:
  KL-redis_data: