services:
  backend:
    image: ghcr.io/bazaaer/klopta-backend:latest
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY}
    labels:
      - "traefik.enable=true"
      # Backend
      - "traefik.http.routers.KL-backend.rule=Host(`${HOSTNAME}`) && PathPrefix(`/api`)"
      - "traefik.http.routers.KL-backend.entrypoints=websecure"
      - "traefik.http.routers.KL-backend.tls=true"
      - "traefik.http.routers.KL-backend.tls.certresolver=letsencrypt"
    restart: unless-stopped
    networks:
      - traefik
  frontend:
    image: ghcr.io/bazaaer/klopta-frontend:latest
    labels:
      - "traefik.enable=true"
      # Frontend
      - "traefik.http.routers.KL-frontend.rule=Host(`${HOSTNAME}`) && !PathPrefix(`/api`)"
      - "traefik.http.routers.KL-frontend.entrypoints=websecure"
      - "traefik.http.routers.KL-frontend.tls=true"
      - "traefik.http.routers.KL-frontend.tls.certresolver=letsencrypt"
    restart: unless-stopped
    networks:
      - traefik

networks:
  traefik:
    external: true