openapi: "3.0.0"
info:
  title: "Backend API"
  description: "API-documentatie voor authenticatie en gebruikersbeheer van de backend"
  version: "1.0.0"
paths:
  /api/login:
    post:
      summary: "Gebruiker login"
      description: "Authenticeert de gebruiker en retourneert een JWT-toegangstoken."
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  description: "De gebruikersnaam van de gebruiker"
                  example: "admin"
                password:
                  type: string
                  description: "Het wachtwoord van de gebruiker"
                  example: "pwd"
      responses:
        "200":
          description: "Succesvolle login"
          content:
            application/json:
              schema:
                type: object
                properties:
                  api_key:
                    type: string
                    description: "JWT-toegangstoken voor geauthenticeerde aanvragen"
        "401":
          description: "Ongeldige inloggegevens"

  /api/revoke_api_key:
    delete:
      summary: "API-sleutel intrekken"
      description: "Trek de API-sleutel van de huidige gebruiker in."
      security:
        - bearerAuth: []
      responses:
        "200":
          description: "API-sleutel succesvol ingetrokken"
        "401":
          description: "Niet geautoriseerd"

  /api/create_user:
    post:
      summary: "Gebruiker aanmaken"
      description: "Maakt een nieuwe gebruiker aan. Alleen toegankelijk voor admin-gebruikers."
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  description: "De gebruikersnaam voor de nieuwe gebruiker"
                  example: "nieuwegebruiker"
                password:
                  type: string
                  description: "Het wachtwoord voor de nieuwe gebruiker"
                  example: "nieuwwachtwoord"
                role:
                  type: string
                  description: "Rol van de nieuwe gebruiker (standaard is 'user')"
                  example: "user"
      responses:
        "201":
          description: "Gebruiker succesvol aangemaakt"
        "400":
          description: "Gebruiker aanmaken mislukt"
        "403":
          description: "Verboden"

  /api/protected:
    get:
      summary: "Beveiligde route"
      description: "Een beveiligde route die authenticatie vereist."
      security:
        - bearerAuth: []
      responses:
        "200":
          description: "Toegang verleend"
        "401":
          description: "Ongeautoriseerde toegang"

  /api/admin:
    get:
      summary: "Admin Route"
      description: "Alleen toegankelijk voor admin-gebruikers."
      security:
        - bearerAuth: []
      responses:
        "200":
          description: "Admin-toegang verleend"
        "403":
          description: "Alleen voor admins"

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
