# Ray Serve Deployment Configuration
proxy_location: EveryNode

http_options:
  host: 0.0.0.0
  port: 8000

logging_config:
  encoding: TEXT
  log_level: INFO
  logs_dir: null
  enable_access_log: true

applications:
- name: combined_pipeline
  route_prefix: /
  import_path: rayserve:pipeline_app 
  runtime_env: {}
  deployments:
  - name: CombinedPipeline
    max_concurrent_queries: 10
    ray_actor_options:
      num_cpus: 1
      num_gpus: 0.1
    autoscaling_config:
      min_replicas: 1
      max_replicas: 10
      target_num_ongoing_requests_per_replica: 20
