services:
  dev-container:
    image: nvidia/cuda:12.6.2-cudnn-devel-ubuntu22.04
    volumes:
      - ..:/workspaces/AppliedAiProject:cached
    environment:
      MONGO_USER: root
      MONGO_PASSWORD: examplepassword
      MONGO_HOST: mongodb
      MONGO_PORT: 27017
    depends_on:
      - mongodb
    networks:
      - internal_network
    runtime: nvidia
    command: sleep infinity

  mongodb:
    image: mongo:6
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: examplepassword
    networks:
      - internal_network

networks:
  internal_network:
    driver: bridge