services:
  dev-container:
    image: gcr.io/kaggle-gpu-images/python:latest
    volumes:
      - workspace_data:/workspace:cached
    environment:
      MONGO_USER: root
      MONGO_PASSWORD: examplepassword
      MONGO_HOST: mongodb
      MONGO_PORT: 27017
    depends_on:
      - mongodb
    networks:
      - internal_network
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    command: sleep infinity  # Keeps the container running

  mongodb:
    image: mongo:6
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: examplepassword
    networks:
      - internal_network

volumes:
  workspace_data:

networks:
  internal_network:
    driver: bridge