services:
  dev-container:
    image: nvidia/cuda:12.6.2-cudnn-devel-ubuntu22.04
    volumes:
      - ..:/workspaces/AppliedAiProject:cached
    environment:
      MONGO_USER: root
      MONGO_PASSWORD: examplepassword
      MONGO_HOST: mongodb
      MONGO_PORT: 27017
    depends_on:
      - mongodb
    networks:
      - internal_network
    runtime: nvidia
    command: sleep infinity

  mongodb:
    image: mongo:6
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: examplepassword
    networks:
      - internal_network

  redis:
    image: "redis:latest"
    volumes:
      - redis_data:/data
    networks:
      - internal_network
      
  ollama:
    image: ollama/ollama:latest
    networks:
      - internal_network
    volumes:
      - ollama_data:/root/.ollama
    runtime: nvidia

volumes:
  ollama_data:
  redis_data:

networks:
  internal_network:
    driver: bridge